package Constants;

public enum Notification {
    CONTACT_REQUEST,JOIN_GROUP_REQUEST,CONTACT_REQ_RESPONSE,JOIN_GROUP_REQ_POS_RESPONSE,JOIN_GROUP_REQ_NEG_RESPONSE,EDIT_USER,EDIT_GROUP,CONTACT_REQ_NEG_RESPONSE,
    MESSAGE,MESSAGE_DELETE,FILE_DELETE,USER_LOGIN,USER_LEFT,GROUP_DELETE,CONTACT_DELETE,LEAVE_GROUP,ACCEPT_MEMBER,NEW_FILE_AVAILABLE;
}
