package Constants;

public enum Notification {
    CONTACT_REQUEST,JOIN_GROUP_REQUEST,CONTACT_REQ_RESPONSE,JOIN_GROUP_REQ_RESPONSE,EDIT_USER,
    MESSAGE,MESSAGE_DELETE,FILE,FILE_DELETE,USER_LOGIN,USER_LEFT,GROUP_DELETE,CONTACT_DELETE,LEAVE_GROUP
}
